#
# Azure Pipelines configuration for building and testing create-react-app on Linux, Windows, and macOS.
#

trigger:
  - master

variables:
  CI: true
  # Overrides the Yarn and NPM cache directories so they are on the same drive as the source. This helps improve build performance on Windows hosted agents.
  YARN_CACHE_FOLDER: $(Build.SourcesDirectory)/../yarn-cache
  NPM_CONFIG_CACHE: $(Build.SourcesDirectory)/../npm-cache
  # Sets TEMP to be on the same drive as the cloned source on Windows. This avoids test scripts that "cd" into a directory under TEMP from failing because this directory is on a different drive from the current directory.
  VSTS_OVERWRITE_TEMP: True
  CRA_INTERNAL_TEST: true

# ******************************************************************************
# Simple test suite
# ******************************************************************************
jobs:
  - template: azure-pipelines-test-job.yml
    parameters:
      name: Simple
      testScript: tasks/e2e-simple.sh

  # ******************************************************************************
  # Installs test suite
  # ******************************************************************************
  - template: azure-pipelines-test-job.yml
    parameters:
      name: Installs
      testScript: tasks/e2e-installs.sh

  # ******************************************************************************
  # Kitchensink test suite
  # ******************************************************************************
  - template: azure-pipelines-test-job.yml
    parameters:
      name: Kitchensink
      testScript: tasks/e2e-kitchensink.sh

  # ******************************************************************************
  # Kitchensink Eject test suite
  # ******************************************************************************
  - template: azure-pipelines-test-job.yml
    parameters:
      name: KitchensinkEject
      testScript: tasks/e2e-kitchensink-eject.sh

  # ******************************************************************************
  # Behavior test suite
  # ******************************************************************************
  - template: azure-pipelines-test-job.yml
    parameters:
      name: Behavior
      testScript: tasks/e2e-behavior.sh
      configurations:
        LinuxNode10: { vmImage: 'ubuntu-16.04', nodeVersion: 10.x }
        LinuxNode12: { vmImage: 'ubuntu-16.04', nodeVersion: 12.x }
        WindowsNode10: { vmImage: 'windows-2019', nodeVersion: 10.x }
        WindowsNode12: { vmImage: 'windows-2019', nodeVersion: 12.x }
        MacNode10: { vmImage: 'macOS-10.15', nodeVersion: 10.x }
        MacNode12: { vmImage: 'macOS-10.15', nodeVersion: 12.x }

  # ******************************************************************************
  # Old Node test suite
  # ******************************************************************************
  - job: OldNode
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: 8.x
        displayName: 'Install Node.js 8.x'
      - bash: tasks/e2e-old-node.sh
        displayName: 'Run tests'
